apiVersion: v1
kind: Service
metadata:
  name: gitlab
  namespace: gitlab
  labels:
    role: web
spec:
  type: LoadBalancer
  selector:
    role: web
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: ssh
      port: 1022
      targetPort: ssh
