apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gitlab-postgresql
  namespace: gitlab
  labels:
    role: data
spec:
  replicas: 1
  template:
    metadata:
      labels:
        role: data
    spec:
      containers:
      - name: postgresql
        image: macadmins/postgres:latest
        imagePullPolicy: Always
        env:
        - name: DB_USER
          value: gitlab
        - name: DB_PASS
          value: r@5@ZSXvX!zEoPjb
        - name: DB_NAME
          value: gitlab_production
        #- name: DB_EXTENSION
        #  value: pg_trgm
        ports:
        - name: postgres
          containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: glusterfs-cluster-gitlab-postgresql-volume
        #livenessProbe:
        #  exec:
        #    command:
        #    - pg_isready
        #    - -h
        #    - localhost
        #    - -U
        #    - postgres
        #  initialDelaySeconds: 30
        #  timeoutSeconds: 5
        #readinessProbe:
        #  exec:
        #    command:
        #    - pg_isready
        #    - -h
        #    - localhost
        #    - -U
        #    - postgres
        #  initialDelaySeconds: 60
        #  timeoutSeconds: 20
      volumes:
      - name: glusterfs-cluster-gitlab-postgresql-volume
        #emptyDir: {}
        persistentVolumeClaim:
          claimName: glusterfs-cluster-gitlab-postgresql-claim
