apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gitlab-redis
  namespace: gitlab
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: gitlab-redis
        role: calc
    spec:
      containers:
      - name: redis
        image: redis:3.2.4
        ports:
        - name: redis
          containerPort: 6379
        volumeMounts:
        - mountPath: /var/lib/redis
          name: glusterfs-cluster-gitlab-redis-volume
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          timeoutSeconds: 1
      volumes:
        - name: glusterfs-cluster-gitlab-redis-volume
          persistentVolumeClaim:
            claimName: glusterfs-cluster-gitlab-redis-claim
